name: MumotEnv
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py35_0
- bleach=2.0.0=py35_0
- entrypoints=0.2.3=py35_1
- html5lib=1.0.1=py_0
- ipython=6.2.1=py35_1
- ipython_genutils=0.2.0=py35_0
- ipywidgets=7.0.5=py35_0
- jedi=0.11.1=py35_0
- jinja2=2.10=py35_0
- jsonschema=2.6.0=py35_0
- jupyter_client=5.2.2=py35_0
- jupyter_core=4.4.0=py_0
- libsodium=1.0.15=1
- markupsafe=1.0=py35_0
- mistune=0.8.3=py_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py35_0
- notebook=5.4.0=py35_0
- pandoc=2.1.1=0
- pandocfilters=1.4.1=py35_0
- parso=0.1.1=py_0
- pexpect=4.3.1=py35_0
- pickleshare=0.7.4=py35_0
- prompt_toolkit=1.0.15=py35_0
- ptyprocess=0.5.2=py35_0
- pygments=2.2.0=py35_0
- pyzmq=16.0.2=py35_3
- send2trash=1.4.2=py_0
- simplegeneric=0.8.1=py35_0
- terminado=0.8.1=py35_0
- testpath=0.3.1=py35_0
- tornado=4.5.3=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- widgetsnbextension=3.1.3=py35_0
- zeromq=4.2.1=1
- certifi=2016.2.28=py35_0
- cycler=0.10.0=py35_0
- decorator=4.1.2=py35_0
- freetype=2.5.5=2
- icu=54.1=0
- ipykernel=4.6.1=py35_0
- libpng=1.6.30=1
- matplotlib=2.0.2=np113py35_0
- mkl=2017.0.3=0
- mpmath=0.19=py35_1
- networkx=1.11=py35_0
- numpy=1.13.1=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- qt=5.6.2=2
- readline=6.2=2
- scipy=0.19.1=np113py35_0
- setuptools=36.4.0=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- sympy=1.1.1=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - antlr4-python3-runtime==4.5.3
  - graphviz==0.8.2
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - pydstool==0.90.2
prefix: /Users/thbo/anaconda/envs/MumotEnv

